cask_args appdir: "/Applications"

tap "homebrew/cask"

brew "lua"
brew "docker-compose"

cask "java8" unless system "/usr/libexec/java_home -v 1.8 --failfast"

cask "docker"
cask "android-studio"
cask "google-chrome"
cask "iina"
cask "synology-drive"
cask "shadowsocksx-ng"