cask_args appdir: "/Applications"

tap "homebrew/cask"

brew "lua"
brew "docker-compose"

cask "java8" unless system "/usr/libexec/java_home -v 1.8 --failfast"

cask "docker"
cask "android-studio"
cask "google-chrome"
cask "iina"
cask "google-backup-and-sync"
cask "shadowsocksx-ng"

mas "Xcode", id: 497799835
mas "iThoughtsX", id: 720669838
mas "NeteaseMusic", id: 944848654
mas "The Unarchiver", id: 425424353
mas "WeChat", id: 836500024