# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.

  config.hostmanager.enabled = true
  config.hostmanager.manage_guest = true
  config.hostmanager.manage_host = true

  config.vm.define "archlinux", primary: true do |archlinux|
    archlinux.vm.box = "archlinux/archlinux"
    archlinux.vm.hostname = "archlinux"
    archlinux.vm.box_check_update = false
    archlinux.vm.network "private_network", ip: "192.168.10.100"
    archlinux.vm.synced_folder "../workspace/", "/vagrant"
    archlinux.vbguest.auto_update = false
    archlinux.vm.provider "virtualbox" do |vb|
      vb.name = "archlinux-nox"
      vb.cpus = 2
      vb.memory = 2048
    end
  end

  config.vm.define "centos", autostart: false do |centos|
    centos.vm.box = "centos/7"
    centos.vm.hostname = "centos"
    centos.vm.box_check_update = false
    centos.vm.network "private_network", ip: "192.168.10.101"
    centos.vm.synced_folder "../workspace/", "/vagrant"
    centos.vbguest.auto_update = false
    centos.vm.provider "virtualbox" do |vb|
      vb.name = "centos-nox"
    end
  end

  config.vm.define "debian", autostart: false do |debian|
    debian.vm.box = "debian/stretch64"
    debian.vm.hostname = "debian"
    debian.vm.box_check_update = false
    debian.vm.network "private_network", ip: "192.168.10.102"
    debian.vm.synced_folder "../workspace/", "/vagrant"
    debian.vbguest.auto_update = false
    debian.vm.provider "virtualbox" do |vb|
      vb.name = "debian-nox"
    end
  end

  #  config.vm.define "ubuntu", autostart: false do |ubuntu|
  #    ubuntu.vm.box = "ubuntu/xenial64"
  #    ubuntu.vm.hostname = "ubuntu"
  #    ubuntu.vm.box_check_update = false
  #    ubuntu.vm.network "private_network", ip: "192.168.10.103"
  #    ubuntu.vm.synced_folder "./workspace/ubuntu", "/vagrant"
  #  end

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # NOTE: This will enable public access to the opened port
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine and only allow access
  # via 127.0.0.1 to disable public access
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  # config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
  #   vb.memory = "1024"
  # end
  #
  # View the documentation for the provider you are using for more
  # information on available options.

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL
end
