cask_args appdir: "/Applications"

tap "railwaycat/emacsmacport"
tap "homebrew/cask-fonts"

brew "neovim"
brew "ag"
brew "aspell"
brew "clang-format"
brew "cscope"
brew "fcitx-remote-for-osx"

cask "emacs-mac-spacemacs-icon"
cask "font-source-code-pro"