cask_args appdir: "/Applications"

tap "homebrew/cask"
tap "caskroom/versions"

brew "lua"

cask "java8" unless system "/usr/libexec/java_home -v 1.8 --failfast"

cask "google-chrome"
cask "iina"
cask "google-backup-and-sync"
cask "shadowsocksx-ng"
